### ISSUE TITLE
Unable to run extension since switching to esbuild from vite

### ISSUE THREAD

**Issue by tomel98** [Debdut/browser-extension#11]
Using the default template I'm unable to load the extension in to any chromium based browser

Steps to reproduce
1. Check out repository at commit d6a42253c0e7f4d70399a83eeda4489c44b9df94
2. npm install
3. npm run start chrome

Expected Outcome
Extension loads in the Chrome browser

Actual Outcome
Chrome displays an error when it launches `Failed to load extenion from {dist}. Could not load Javascript '' for content script`

Workaround
1. Revert to commit a49bc54be04f9cdbee14d245c51c35b4b36279f9 when it was using Vite.
2. npm install
3. npm run start chrome
4. Browser launches with no errors and extension is loaded

**Comment by Debdut** [comment]
Try now, should work. Reopen if not!

**Comment by tomel98** [comment]
Hi @Debdut 

Thanks for looking into this.

It still seems to be a problem with the latest commit.

Note: This may only affect Windows due to how it handles relative paths.

The generated manifest includes relative paths like "content\\index.js" and "background\\index.js" which gives the error `Failed to load extenion from {dist}. Could not load Javascript '' for content script`

If I manually change the paths to use forward slashes (e.g. "content/index.js"), then the error is resolved.

I made the following change in build.ts (BuildManifest)

```
    pageDistMap[name] = pageDist.replace("\\", "/");
    pageDistMap[`${name}-css`] = cssDist.map((x) => x.replace("\\", "/"));
```

Let me know if you want me to open a PR or you'd prefer to fix it a different way.
