### ISSUE TITLE
Manifest doesnt update after autoreload

### ISSUE THREAD

**Issue by fishuke** [Debdut/browser-extension#13]
Manifest doesnt update after autoreload, html file updated but manifest file refers to old file.

**Comment by fishuke** [comment]
Note: reverted to revision a49bc54be04f9cdbee14d245c51c35b4b36279f9 and it works. After commit somewhere it is broken.

**Comment by Debdut** [comment]
It broke other things! Manual reloads after manifest update, sorry! I'll welcome a PR though.

**Comment by harismuha123** [comment]
@Debdut any news on the reloads fix? or a suggestion maybe?
