### ISSUE TITLE
Every time I save the popup I get error: file can not be accessed

### ISSUE THREAD

**Issue by francoisbeyers** [Debdut/browser-extension#14]
`Your file couldn’t be accessedIt may have been moved, edited or deleted.
ERR_FILE_NOT_FOUND`

Then I have to stop the server and start it again and then the popup shows the update. What am I doing wrong here?
I followed the steps:
```
# Install packages
npm install

# Live Dev for multiple browsers
npm run start [browser]
# npm run start brave
```
I've even tried to do a build and then `npm run start brave` again, but that does change either. Would appreciate any help. 
This is a great boilerplate

**Comment by Debdut** [comment]
wow that's strange, will take a look this weekend ✌️

**Comment by francoisbeyers** [comment]
Thank you @Debdut It is most likely something I am doing, but I can't seem to figure it out. And I would really just like to use your boilerplate code, than recreating the whole thing from scratch. 🙏

**Comment by nascarsayan** [comment]
@francoisbeyers, can you provide the repro steps? Also, it should be working in Linux now, after #12 . Thanks!

**Comment by alexburlis** [comment]
Same thing for me unfortunately:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/34502316/229113991-b48d881b-a273-40f7-8c62-83439ec980fe.png">

Clean download. Ran _npm i_ and changed a single character in the popup - nothing else.

Edit: I tried a bunch of things now. It seems that the hot reload is not pushing all the changes correctly. Even after deleting the popup folder completely, I get this

<img width="203" alt="image" src="https://user-images.githubusercontent.com/34502316/229120752-5e211410-9d32-4a5d-8dfb-96f1221f7af2.png">

**Comment by Debdut** [comment]
Can you chime in your system info?

**Comment by alexburlis** [comment]
Tested on a Macbook Pro M1 Max as well as my Windows Desktop with newest Chrome and fresh npm installs without nvm. Let me know if you need specific details!
Appreciate you taking the effort to look into this.

**Comment by helloworld** [comment]
+1, experiencing the same thing here. Can repro the issue with a Macbook Pro M1 with the newest chrome w/ fresh npm install. Thanks for taking a look at this!

**Comment by jsegura** [comment]
Same here. Let me know if i can help debugging the issue.
