### ISSUE TITLE
Safari Xcode project?

### ISSUE THREAD

**Issue by theowenyoung** [Debdut/browser-extension#17]
Hi, thanks for the great project, I tried to build for safari, but there is only js/html files, how do I make a xcode project from it?

**Comment by Debdut** [comment]
Note safari build doesn't auto reload because of Xcode.

```sh
npm run build chrome
cd dist
/Applications/Xcode-14.1.0.app/Contents/Developer/usr/bin/safari-web-extension-converter chrome
```

Change the above path with your Xcode path.
