### ISSUE TITLE
Fix build on windows platform

### ISSUE THREAD

**Issue by BurtHarris** [Debdut/browser-extension#2]
Wow!  I've been looking for a template like this.   It has more than I could have hoped for.  Thank you.

The build scripts in package.json currently don't work on Windows, and the fix is simple.  There are well-known npm packages to solve them.  ***cross-env***, ***mkdirp***, and ***rimraf*** are cross-platform replacements for just such occasions.

I want to contribute back, so I'll try to submit a PR shortly.

**Comment by Debdut** [comment]
Thanks, a PR will be awesome 🙏🏻

**Comment by nascarsayan** [comment]
It should now be working on mac, windows and linux platforms.
