### ISSUE TITLE
Problem using React component in content scripts

### ISSUE THREAD

**Issue by pixelkoduje** [Debdut/browser-extension#9]
I have a problem using React components in content scripts. It seems to me that this is the most natural use of the script, in this case.

```
Uncaught SyntaxError: Cannot use import statement outside a module (at index.js:1:1)`

import { createRoot } from 'react-dom/client';
import Main from './Main';

const container = document.createElement('div')
const rootEl = document.createElement('div')
const styleEl = document.createElement('link')
const shadowDOM = container.attachShadow?.({ mode: 'open' }) || container
styleEl.setAttribute('rel', 'stylesheet')
styleEl.setAttribute('href', chrome.runtime.getURL('contentStyle.css'))
shadowDOM.appendChild(styleEl)

shadowDOM.appendChild(rootEl)
document.body.appendChild(container)

const root = createRoot(container); // createRoot(container!) if you use TypeScript
root.render(<Main/>);
```

How to solve it?

**Comment by pixelkoduje** [comment]
You can confirm by putting this code in index.tsx in content. It will not work.

**Comment by pixelkoduje** [comment]
I would appreciate information on how to make it work.

**Comment by Debdut** [comment]
Thanks for reporting, will look into this asap!

**Comment by KULTI1995** [comment]
Please, I want to use this in my project.

**Comment by KULTI1995** [comment]
I will be grateful for information on how this will be implemented.

**Comment by Debdut** [comment]
Fixed!

**Comment by M-Moeez** [comment]
can you tell me which commit you made for the fix, since i got a project that is using this template but they are using vite and i need to add imports/react components  in content scrip

**Comment by M-Moeez** [comment]
@pixelkoduje were you able to get it to work ?
